### ISSUE TITLE
UX 관련 및 잔버그 수정 ~ 10/25(금)

### ISSUE THREAD

**Issue by SugarSyrup** [F-orever/gabozago_FE#374]
## 어떤 버그인가요?

UX 관련 및 잔버그 수정

## 어떤 상황에서 발생한 버그인가요?

- [x] 유저 정보 수정 페이지 - kakao 로그인 메시지 변경
- [x] api URL 수정된 부분 반영
- [x] 내 일정에 추가히 버튼 클릭 시 location 가져오기
- [x] 내 여행에서 검색해서 나온 결과 location 이랑 매칭 및 팝업 표시
- [x] 스크랩-여행장소탭에서 편집하기 진입시 취소-삭제하기 바 상단에 스티키되도록 
- [x] 스크랩-여행장소탭-편집하기에서 셀렉 시 O 아이콘을 클릭해야하는데 전체 장소 아이템을 클릭해도 셀렉되도록
- [x] 콘텐츠탭 상세페이지(2번사진)에서 인스타그램 바로가기를 콘텐츠 아이템 전체를 클릭해도 이동하도록 수정
- [x] 콘텐츠 탭 이미지 비율 맞춤 말고 자르기 (object-fit: cover)
- [x] urlEncode()

## 예상 결과

> 예상했던 정상적인 결과가 어떤 것이었는지 설명해주세요

## 참고할만한 자료(선택)

디스코드 링크 : (https://discord.com/channels/1181930066746294402/1182244202797604914/1298556292729667658)[https://discord.com/channels/1181930066746294402/1182244202797604914/1298556292729667658]

**Comment by chodakk** [comment]
### 추가된 태스크
- [ ] 콘텐츠탭 상세페이지, 하단 여백 부족
- [ ] 장소 상세페이지, isScraped=False 시 해당 페이지 내 메모 ui 제외시키기
- [ ] 아티클 본문 내 장소 카드 url 수정 ([링크](https://www.notion.so/teamfore/community-article-place-place_id-7e1b6cb8e160486fb428ef6b240d00d2?pvs=4))
